# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flightclub < Formula
  desc ""
  homepage "https://github.com/mkmik/flightclub"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.3/flightclub_0.0.3_darwin_amd64.tar.gz"
      sha256 "abf14ec79b01ec31793b612669813c8beac09356da1d9c6f59dac1b3b2687ead"

      def install
        bin.install "flightclub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.3/flightclub_0.0.3_darwin_arm64.tar.gz"
      sha256 "60277f154699ac0f5644c423ab39583f9ce9f8029563ae4de96ccbf77869a0e6"

      def install
        bin.install "flightclub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.3/flightclub_0.0.3_linux_amd64.tar.gz"
      sha256 "0f98164011ded750ba5807153bf2b3b500ab2e6f7b56d73365ba55f1a111d03b"

      def install
        bin.install "flightclub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.3/flightclub_0.0.3_linux_arm64.tar.gz"
      sha256 "2c524acfea1bf414864c598e681bed9ba2564446666612d5fa77dcf14e073237"

      def install
        bin.install "flightclub"
      end
    end
  end
end
