# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flightclub < Formula
  desc ""
  homepage "https://github.com/mkmik/flightclub"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.5/flightclub_0.0.5_darwin_arm64.tar.gz"
      sha256 "6b27d142b296e84d8662576686d094eeeef10920c9c36bf1741784af6de28426"

      def install
        bin.install "flightclub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.5/flightclub_0.0.5_darwin_amd64.tar.gz"
      sha256 "48957fd88b64e4d5fb12824b55af08c529844dac0c306d9418a393a4d2e78264"

      def install
        bin.install "flightclub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.5/flightclub_0.0.5_linux_amd64.tar.gz"
      sha256 "0df01ac7fc61888048ef802138cbdfd933273091e7d704a20725b2c5528cba59"

      def install
        bin.install "flightclub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mkmik/flightclub/releases/download/v0.0.5/flightclub_0.0.5_linux_arm64.tar.gz"
      sha256 "983b70209336c4e20ed297a650bc8e296e4ec0621b57e70b7ad884dc40136823"

      def install
        bin.install "flightclub"
      end
    end
  end
end
